var g = new Graph('myGraph');
g.add('foo');
g.connect('foo', 'bar', 'baz', 'grault','zork');
g.connect('grault', 'qux','quux');
g.connect('zork','smee','prosser','gru','phee','bor');
g.connect('foo','a');
g.connect('foo','a1');
g.connect('foo','a2');
g.connect('foo','a3');

g.connect('a','b');
g.connect('b','c');
g.connect('c','d');
g.connect('d','e');
g.connect('e','f');
g.connect('f','g');
g.connect('g','h');
g.connect('h','i');
g.connect('i','j');
g.connect('j','k');
g.connect('k','l');
g.connect('l','m');
g.connect('f','n');
g.connect('g','n');
g.connect('h','n');
g.connect('i','n');
g.connect('j','n');

g.connect('a1','b1');
g.connect('b1','c1');
g.connect('c1','d1');
g.connect('d1','e1');
g.connect('e1','f1');
g.connect('f1','g1');
g.connect('g1','h1');
g.connect('h1','i1');
g.connect('i1','j1');
g.connect('j1','k1');
g.connect('k1','l1');
g.connect('l1','m1');
g.connect('f1','n1');
g.connect('g1','n1');
g.connect('h1','n1');
g.connect('i1','n1');
g.connect('j1','n1');

g.connect('a2','b2');
g.connect('b2','c2');
g.connect('c2','d2');
g.connect('d2','e2');
g.connect('e2','f2');
g.connect('f2','g2');
g.connect('g2','h2');
g.connect('h2','i2');
g.connect('i2','j2');
g.connect('j2','k2');
g.connect('k2','l2');
g.connect('l2','m2');
g.connect('f2','n2');
g.connect('g2','n2');
g.connect('h2','n2');
g.connect('i2','n2');
g.connect('j2','n2');

g.connect('a3','b3');
g.connect('b3','c3');
g.connect('c3','d3');
g.connect('d3','e3');
g.connect('e3','f3');
g.connect('f3','g3');
g.connect('g3','h3');
g.connect('h3','i3');
g.connect('i3','j3');
g.connect('j3','k3');
g.connect('k3','l3');
g.connect('l3','m3');
g.connect('f3','n3');
g.connect('g3','n3');
g.connect('h3','n3');
g.connect('i3','n3');
g.connect('j3','n3');


g.nodes.baz.url = 'http://google.com';
g.nodes.bar.url = 'http://yahoo.com';